# Generated by Django 4.0.4 on 2022-05-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='name',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='offer',
        ),
    ]
